- constants/commands.js
- package.json
The image entry point changed in archway-network/archway@e749fa0
> Update Docker image command

- util/new.js
Depends on https://github.com/archway-network/archway-templates/pull/4
> Add cw721 templates to `archway new` command

- .eslintrc.json
- constants/commands.js
- constants/config.js
- constants/prompt.js
- main.js
- package.json
- util/accounts.js
- util/build.js
- util/configure.js
- util/deploy.js
- util/deployments.js
- util/faucet.js
- util/network.js
- util/new.js
- util/query.js
- util/script.js
- util/test.js
- util/tx.js
> 1.0.5-beta

- .github/workflows/check.yml
- .github/workflows/publish.yml
- package.json
Create a Github workflow for testing and deploying packages to `npm`.
> Configure CI/CD pipeline

- src/clients/archwayd.js
- src/commands/deploy.js
- src/commands/faucet.js
- src/commands/tx.js
- src/index.js
Apply the same patterns as in the `deploy` command to the `tx` command for a smoother user experience.
> Refactor tx command

- package-lock.json
- package.json
- src/commands/faucet.js
- Fix for faceut requests returning `Error: decoding bech32 failed: checksum failed.`
> Release 1.0.8-beta

- .eslintrc.json
- src/clients/archwayd/index.js
- src/clients/archwayd/keys.js
- src/clients/archwayd/query.js
- src/clients/archwayd/tx.js
- src/clients/cargo.js
- src/commands/__tests__/build.test.js
- src/commands/__tests__/instantiate.test.js
- src/commands/__tests__/new.test.js
- src/commands/__tests__/store.test.js
- src/commands/configure.js
- src/commands/deploy.js
- src/commands/deployments.js
- src/commands/instantiate.js
- src/commands/metadata.js
- src/commands/network.js
- src/commands/new.js
- src/commands/query.js
- src/commands/script.js
- src/commands/store.js
- src/commands/tx.js
- src/index.js
- src/util/child_process.js
- src/util/config.js
- src/util/fs.js
- src/util/prompts.js
- src/util/scripts.js
- src/util/semvar.js
- src/util/validators.js
> Add extra linter rules

- src/commands/__tests__/new.test.js
- src/commands/new.js
> Remove git commit from new command

- README.md
- package-lock.json
- src/clients/cargo.js
- src/commands/__tests__/build.test.js
- src/commands/build.js
- src/commands/deploy.js
- Fix for `Error: Process exited with code 101`
- Update docs with the correct dependencies list
> Fixes cargo child process error during build

- src/commands/__tests__/new.test.js
- src/commands/new.js
Added escrow option to `archway new`
Fixed `cargo generate` to generate from URL
Closes https://github.com/archway-network/archway-templates/issues/12
> added escrow option

- src/index.js
- src/util/semvar.js
> Skip automatic version check with env var

- package-lock.json
> Update project dependencies

- src/clients/archwayd/__tests__/fixtures/query-rewards-estimate-fees.json
- src/clients/archwayd/__tests__/query.test.js
- src/clients/archwayd/__tests__/tx.test.js
- src/clients/archwayd/query.js
- src/clients/archwayd/tx.js
- src/networks/data/testnet.constantine.json
- src/networks/data/testnet.titus.json
- src/networks/data/testnet.torii.json
> feat: use the minimum gas fee in all transactions

- src/clients/archwayd/__tests__/tx.test.js
- src/clients/archwayd/tx.js
- src/commands/metadata.js
- src/index.js
> feat: set metadata using the new rewards module

- src/clients/wasm_optimizer.js
The build process was failing when the optimizer image didn't exist in the local environment.
> fix(build): pull the CosmWasm Optimizer image

- src/util/semvar.js
> fix(semvar): check for newer versions using semver

- src/commands/__tests__/new.test.js
- src/commands/new.js
- src/index.js
> fix(new): remove Docker support for new projects

- CODE_OF_CONDUCT.md
Adopted from https://www.contributor-covenant.org/
Related to #93
> chore: add Contributor Covenant Code of Conduct

- src/commands/accounts/balances/get.ts
- src/domain/Accounts.ts
- test/commands/accounts/balances.test.ts
> fix(accounts): allow querying balances from any valid address

- src/domain/SchemaValidation.ts
Deployed and tested messages with the following types:
- boolean
- u8
- u16
- u32
- u64
- i8
- i16
- i32
- i64
- char
- str
- tuple
- array
- Box
- Vec
- Option
- cosmwasm_std::Addr
- cosmwasm_std::CanonicalAddr
- cosmwasm_std::Coin
- cosmwasm_std::DecCoin
- cosmwasm_std::Decimal
- cosmwasm_std::Decimal256
- cosmwasm_std::DenomUnit
- cosmwasm_std::Empty
- cosmwasm_std::IbcChannel
- cosmwasm_std::IbcEndpoint
- cosmwasm_std::Int64
- cosmwasm_std::Int128
- cosmwasm_std::Int256
- cosmwasm_std::Int512
- cosmwasm_std::Timestamp
- cosmwasm_std::Uint64
- cosmwasm_std::Uint128
- cosmwasm_std::Uint256
- cosmwasm_std::Uint512
- cosmwasm_std::WeightedVoteOption
Closes #227
> fix(contracts): schema validation test and update

- src/commands/accounts/list.ts
- src/commands/accounts/remove.ts
- src/domain/Accounts.ts
- src/domain/keystore/index.ts
- src/types/Account.ts
> fix(accounts): delete account by checking name/address only

- src/commands/accounts/balances/send.ts
- src/commands/accounts/remove.ts
- src/commands/contracts/store.ts
- src/parameters/flags/transaction.ts
> fix(contracts): use same no-confirm flag on txs and commands

- src/commands/contracts/execute.ts
- src/commands/contracts/instantiate.ts
- src/commands/contracts/migrate.ts
- src/commands/contracts/query/smart.ts
- src/domain/Contracts.ts
- src/exceptions/ErrorCodes.ts
- src/exceptions/MigrateError.ts
- src/exceptions/index.ts
- src/parameters/flags/contracts.ts
- test/commands/contracts/execute.test.ts
- test/commands/contracts/instantiate.test.ts
- test/commands/contracts/migrate.test.ts
- test/commands/contracts/query/smart.test.ts
- test/integration/contractsAndRewards.sh
> fix(contracts): update --no-validation flags

- CHANGELOG.md
- src/hooks/postrun/versionCheck.ts
Fixed the version check hook storing the current version on cache
> fix: cache of version check hook
